ALTER TABLE user_preferences
    ADD COLUMN IF NOT EXISTS recording_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS data_retention_days INTEGER NOT NULL DEFAULT 30,
    ADD COLUMN IF NOT EXISTS allow_model_training BOOLEAN NOT NULL DEFAULT FALSE;

